import { test, expect } from '@playwright/test';
import adminHelpers from '../helpers/admin';

test('Admin - Roles CRUD (create, update, delete role)', async ({ page }) => {
  // Accept native JS dialogs (confirm) automatically
  page.on('dialog', async (dialog) => {
    await dialog.accept();
  });

  await adminHelpers.loginAsAdminViaIdP(page);

  // Navigate directly to the Admin Roles page
  await page.goto('https://localhost:7035/Admin/Roles');
  await page.waitForURL(/\/Admin\/Roles/);

  // Wait for the Vue app to load
  await page.waitForSelector('button:has-text("Create Role"), table', { timeout: 15000 });

  const roleName = `e2e-role-${Date.now()}`;
  const description = `E2E Test Role ${Date.now()}`;

  // Click the Create Role button
  await page.click('button:has-text("Create Role")');

  // Wait for the modal to appear (CreateRoleModal uses id selectors)
  await page.waitForSelector('#name', { timeout: 5000 });

  // Wait for permission inputs to be loaded and visible

  // Fill in the role name and description
  await page.fill('#name', roleName);
  await page.fill('#description', description);

  // Select some permissions (checkboxes)
  // Wait for permissions section to load - permissions are grouped by category
  await page.waitForSelector('input[type="checkbox"]', { timeout: 5000 });
  // Select two well-known permissions explicitly to make this deterministic
  // Wait for permission inputs to be loaded and visible
  await page.waitForSelector('input[id^="perm-"]', { timeout: 20000 });
  await page.waitForSelector('#perm-users\\.read', { timeout: 20000 });
  await page.waitForSelector('#perm-roles\\.read', { timeout: 20000 });
  // Use the checkbox ids generated by the UI: 'perm-{permission}' (dots must be escaped in selectors)
  // Check using force to avoid issues with off-screen/scrollable modal internals
  await page.check('input[id="perm-users.read"]', { force: true });
  await page.check('input[id="perm-roles.read"]', { force: true });

  // Submit the form
  await page.click('button[type="submit"]');

  // Wait for modal to close and API to complete
  await page.waitForTimeout(2000);

  // Verify role was created via API (table might be paginated) and capture API item + UI locator
  const roleFetch = await page.evaluate(async (name) => {
    const resp = await fetch(`/api/admin/roles?search=${encodeURIComponent(name)}`);
    if (!resp.ok) return null;
    return resp.json();
  }, roleName);
  expect(roleFetch).not.toBeNull();
  const apiItem = Array.isArray(roleFetch) ? (roleFetch[0] ?? null) : (roleFetch.items && roleFetch.items.length > 0 ? roleFetch.items[0] : null);
  expect(apiItem).not.toBeNull();
  const roleApiItem = apiItem;

  // Find the UI row reliably (handles tables and pagination)
  const roleRow = await adminHelpers.searchListForItem(page, 'roles', roleName, { listSelector: 'table tbody', timeout: 10000 });
  expect(roleRow).not.toBeNull();
  if (roleRow) await expect(roleRow).toBeVisible({ timeout: 10000 });
  const row = roleRow!;

  // Click the edit button (look for Edit action button)
  await row.locator('button[title*="Edit"], button:has-text("Edit")').first().click();

  // Update the description
  const updatedDescription = `${description} (updated)`;
  await page.waitForSelector('#description');
  await page.fill('#description', updatedDescription);

  // Add another explicit permission in the Edit modal
  await page.check('input[id="perm-roles.update"]', { force: true });

  // Submit the update
  await page.click('button[type="submit"]');

  // Verify the update — fetch the updated role explicitly by ID (deterministic)
  const updatedRole = await page.evaluate(async (id) => {
    const r = await fetch(`/api/admin/roles/${id}`);
    if (!r.ok) return null;
    return r.json();
  }, roleApiItem.id);
  expect(updatedRole).not.toBeNull();
  if (updatedRole) {
    expect(updatedRole.permissions?.length ?? 0).toBe(3);
  }

  // Also assert the UI permissions column explicitly (3rd table column should show the count)
  const permissionsCell = row.locator('td').nth(2);
  await expect(permissionsCell).toContainText('3', { timeout: 20000 }); // 3 permissions now
  

  // Delete the role: use searchAndClickAction to click the Delete button; fallback to a direct click in the
    // Delete the role: log row debug info and use searchAndClickAction to click the Delete button; fallback to a direct click in the
  // row if the helper didn't find it (keeps behavior aligned with historical implementation)
    const actionTexts = await row.locator('button, a, li').allInnerTexts().catch(() => []);
  
    // For roles, the Delete button often has a title 'Delete Role' (icon-only). Try a targeted locator first.
    const deleteBtnExact = row.locator('button[title*="Delete Role"], button[title*="Delete"]');
    if (await deleteBtnExact.count() > 0) {
      await deleteBtnExact.first().click();
    } else {
      // fallback to the generic search-and-confirm helper
      const deleteResult = await adminHelpers.searchAndConfirmAction(page, 'roles', roleName, 'Delete', { listSelector: 'ul[role="list"], table tbody', timeout: 5000 });
      
      if (!deleteResult.clicked) {
        console.warn('Delete button not found via exact title or helper; role not deleted via UI.');
      }
    }

  // Confirm deletion if a confirmation modal is shown; otherwise rely on native JS dialog handling
  const confirmBtn = page.locator('button:has-text("Delete"):not([disabled])').first();
  if (await confirmBtn.count() > 0 && await confirmBtn.isVisible()) {
    await confirmBtn.click();
  }

  // Wait for the role to be removed from the table
  try {
    const removed = await adminHelpers.searchListForItem(page, 'roles', roleName, { listSelector: 'table tbody', timeout: 20000 });
    expect(removed).toBeNull();
  } catch (e) {
    // If UI delete fails, fall back to the API cleanup
    console.warn(`UI delete failed for role ${roleName}, attempting API cleanup...`);
    await adminHelpers.deleteRole(page, roleName);
  }
});
