version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /Web.IdP
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker-compose
    directory: /deployment
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
